const weatherCodeMap={0:['晴朗','☀','sunny'],1:['大致晴朗','⛅','sunny'],2:['局部多云','⛅','cloudy'],3:['阴天','☁','cloudy'],45:['有雾','☁','cloudy'],48:['雾凇','☁','cloudy'],51:['毛毛雨','☔','rainy'],53:['毛毛雨','☔','rainy'],55:['毛毛雨','☔','rainy'],61:['小雨','☔','rainy'],63:['中雨','☔','rainy'],65:['大雨','☔','rainy'],80:['阵雨','☔','rainy'],81:['阵雨','☔','rainy'],82:['强阵雨','☔','rainy'],95:['雷雨','⛈','rainy']};
const getWeatherMeta=code=>weatherCodeMap[code]||['未知','☁','cloudy'];
const windName=deg=>['北风','东北风','东风','东南风','南风','西南风','西风','西北风'][Math.round(deg/45)%8];
const formatTime=value=>value?value.slice(11,16):'--:--';
const formatDate=value=>new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric'}).format(new Date(value+'T12:00:00'));
const formatDay=(value,index)=>index===0?'今天':new Intl.DateTimeFormat('zh-CN',{weekday:'short'}).format(new Date(value+'T12:00:00'));
const uvText=value=>value<3?'较弱':value<6?'中等':value<8?'较强':'很强';
function renderForecast(daily){document.querySelector('#forecast-list').innerHTML=daily.time.slice(0,7).map((date,index)=>{const meta=getWeatherMeta(daily.weather_code[index]);return '<div class="forecast-row"><span class="forecast-day">'+formatDay(date,index)+'</span><span class="forecast-date">'+formatDate(date)+'</span><span class="weather-symbol '+meta[2]+'">'+meta[1]+' <small>'+meta[0]+'</small></span><span class="temp-range"><b>'+Math.round(daily.temperature_2m_max[index])+'°</b><i class="temp-track"></i></span><span class="forecast-low">'+Math.round(daily.temperature_2m_min[index])+'°</span></div>'}).join('')}
function renderHourly(hourly){const start=Math.max(0,hourly.time.findIndex(time=>time>=new Date().toISOString().slice(0,13)));document.querySelector('#hourly-chart').innerHTML=hourly.time.slice(start,start+7).map((time,index)=>{const chance=hourly.precipitation_probability[start+index]||0;return '<div class="hour"><b>'+chance+'%</b><div class="bar-wrap"><i class="bar" style="height:'+Math.max(10,chance*2)+'%"></i></div><small>'+(index===0?'现在':time.slice(11,16))+'</small></div>'}).join('')}
async function loadWeather(city='衡阳'){document.querySelector('#updated-time').textContent='正在更新';try{const geo=await fetch('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(city)+'&count=1&language=zh&format=json').then(r=>r.json());if(!geo.results?.length)throw new Error('未找到城市');const place=geo.results[0];const params='latitude='+place.latitude+'&longitude='+place.longitude+'&timezone=Asia%2FShanghai&forecast_days=7&current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m,wind_direction_10m,visibility&hourly=precipitation_probability&daily=weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset,uv_index_max,precipitation_probability_max';const data=await fetch('https://api.open-meteo.com/v1/forecast?'+params).then(r=>r.json());const current=data.current,daily=data.daily,meta=getWeatherMeta(current.weather_code);document.querySelector('#city-name').textContent=place.name+'市';document.querySelector('#temp').textContent=Math.round(current.temperature_2m);document.querySelector('#feels').textContent=Math.round(current.apparent_temperature)+'°';document.querySelector('#condition').textContent=meta[0];document.querySelector('#humidity').textContent=current.relative_humidity_2m;document.querySelector('#humidity-meter').style.width=current.relative_humidity_2m+'%';document.querySelector('#wind').textContent=Math.round(current.wind_speed_10m);document.querySelector('#wind-direction').textContent=windName(current.wind_direction_10m);document.querySelector('#visibility').textContent=(current.visibility/1000).toFixed(1);document.querySelector('#visibility-level').textContent=current.visibility>8000?'清晰':'一般';document.querySelector('#uv').textContent=Math.round(daily.uv_index_max[0]);document.querySelector('#uv-level').textContent=uvText(daily.uv_index_max[0]);document.querySelector('#sunrise').textContent=formatTime(daily.sunrise[0]);document.querySelector('#sunset').textContent=formatTime(daily.sunset[0]);document.querySelector('#rain-chance').textContent=(daily.precipitation_probability_max[0]||0)+'%';document.querySelector('#today-label').textContent=new Intl.DateTimeFormat('zh-CN',{weekday:'long',month:'long',day:'numeric'}).format(new Date())+' · '+place.name;document.querySelector('#updated-time').textContent='刚刚更新';renderForecast(daily);renderHourly(data.hourly)}catch(error){document.querySelector('#updated-time').textContent='更新失败';document.querySelector('#condition').textContent='暂无法获取天气';console.warn(error)}}
document.querySelector('#city-search').addEventListener('keydown',event=>{if(event.key==='Enter'&&event.target.value.trim()){loadWeather(event.target.value.trim());event.target.value=''}});
loadWeather();
